name: Auto Assign Author

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  pr-auto-author-assign:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: toshimaru/auto-author-assign@v2.1.0
