name: Auto Assign Author

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-auto-author-assign:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: technote-space/assign-author@v1
